- apps/web/src/pages/legal.tsx
> Update terms of service

- README.md
- apps/web/.env
- apps/web/.env.testing
- apps/web/README.md
- apps/web/next.config.js
- apps/web/src/pages/legal.tsx
- packages/ipfs-service/src/gateway.ts
Added a couple of small readme updates, and also updated the ipfs gateway urls.
Added a couple of small readme updates for further context and clarification. IPFS gateway urls are updated to reflect the recent changes required for the new gateway subdomain.
> Update readme and ipfs gateway url

- .github/contributing.md
Figma file is stored on a separate instance (opensource@zora.co) and should not pose any IP issues according to shahab.
Make design files public in the spirit of open-source and public goods.
> Add "Nouns Builder designs" section to Contributing Guideline

- apps/web/src/constants/cacheTimes.ts
- apps/web/src/pages/dao/[token]/[tokenId].tsx
- apps/web/src/pages/dao/[token]/index.tsx
- apps/web/src/pages/dao/[token]/vote/[id].tsx
adds 'Cache-Control' to DAO token page and proposal detail page.
fixes #123 
would love some second thoughts on cache times
> Add caching to dao and proposal pages

- apps/web/src/data/contract/requests/getDaoOgMetadata.ts
Fix proposal count for daos with no proposals
This was throwing an exception and resulting in 404s on dao pages for daos with no proposals
> Fix proposal count for no proposals

- apps/web/src/pages/api/og/dao.tsx
- apps/web/src/pages/api/og/proposal.tsx
Fix DAO image aspect ratio for OG images
#166 
- are DAO images correctly displaying in the right aspect ratio
> Fix DAO image aspect ratio for OG images

- apps/web/src/modules/dao/components/About/About.tsx
Add helper text when no founders allocation is present
#182
> Add helper text when no founders allocation is present

- apps/web/src/modules/create-proposal/components/TransactionForm/CustomTransaction/CustomTransaction.tsx
- apps/web/src/modules/create-proposal/components/TransactionForm/CustomTransaction/forms/Function/Function.tsx
Changes create proposal module to use function signautres instead of function names in the function selection dropdown.
fixes #192 
- does this change fix issues with duplicate functions
- is calldata still being generated correctly
- do non duplicate functions still work
- are there issues with formatting now that function names may be significantly longer
> Fix duplicate function names for custom transactions

- apps/web/src/constants/cacheTimes.ts
- apps/web/src/modules/proposal/components/ProposalDescription/DecodedTransactions.tsx
- apps/web/src/pages/api/decode.ts
Adds a new endpoint to decode proposal calldata and remove reliance on ether.actor
closes #201 
- is calldata being properly deocded
- are cache times appropriate
> Add decode calldata endpoint

- apps/web/src/modules/create-proposal/components/Queue/Queue.tsx
- apps/web/src/modules/create-proposal/components/TransactionCard.tsx
Updates transaction queue with clearer modal controls and buttons
closes #296
- does the close modal button work
- does the clear transactions button work
> Update transaction queue modal

- apps/web/src/modules/proposal/components/ProposalActions/ProposalActions.tsx
- apps/web/src/modules/proposal/components/ProposalActions/VoteStatus/VoteStatus.tsx
Removes holder requirement for execute / queue actions
closes #205
- Are queue / execute actions public?
- Are any other actions made public that should still be private?
> Update proposal view to make queue / execute actions public

- apps/web/src/modules/create-dao/components/AuctionSettingsForm/AuctionSettingsForm.schema.ts
Quorum was not validating properly due to `min` and `moreThan` tests being mutually exclusive in yup.
fixes #209 
Does quorum properly validate
> Fix quorum validation

- apps/web/src/modules/proposal/components/ProposalVotes/ProposalVotes.tsx
Reverse order of votes array to show newest votes first
fixes #225
> Update voting list order to show newest first

- apps/web/src/hooks/useVotes.ts
- apps/web/src/modules/dao/components/Activity/Activity.tsx
- apps/web/src/modules/proposal/components/ProposalActions/ConnectWalletAction.tsx
- apps/web/src/modules/proposal/components/ProposalActions/ProposalActions.tsx
- apps/web/src/styles/Proposals.css.ts
Fixes multiple issues around delegation / voting
- improves delegation ui by making delegation and submit proposal buttons more distinct
- improves helper text around delegation / submitting proposals
- fixes issue where delegation was not shown when voter was below threshold but still owned a token
- adds connect wallet action when a user is on an open proposal page without a connected wallet
- fixes a bug in useVotes hook where isOwner and hasThreshold seemed to be swapped
fixes #251
fixes #250
- does the delegation / proposal submission helper text show under the right conditions?
- is the delegation button shown when a voter is below threshold and owns a token?
- does the connect wallet action function properly
- does the useVotes change introduce any issues is other pages?
> Improve delegation / voting ux

- .prettierignore
- README.md
- apps/subgraph/.env.example
- apps/subgraph/.gitignore
- apps/subgraph/README.md
- apps/subgraph/abis/Auction.json
- apps/subgraph/abis/Governor.json
- apps/subgraph/abis/Manager.json
- apps/subgraph/abis/MetadataRenderer.json
- apps/subgraph/abis/Token.json
- apps/subgraph/abis/Treasury.json
- apps/subgraph/docker-compose.yml
- apps/subgraph/networks.json
- apps/subgraph/package.json
- apps/subgraph/schema.graphql
- apps/subgraph/src/auction.ts
- apps/subgraph/src/governor.ts
- apps/subgraph/src/manager.ts
- apps/subgraph/src/metadata.ts
- apps/subgraph/src/token.ts
- apps/subgraph/subgraph.yaml
- apps/subgraph/tsconfig.json
- apps/web/package.json
- pnpm-lock.yaml
Adds a subgraph to replace Zora API calls
Prepare for upcoming protocol changes
- do api requests match zora api data [testing guide here](https://neokry.notion.site/Subgraph-testing-a4adc527560d45fbb5f89b4fa5d16252?pvs=4)
- is the subgraph data structured properly
- does the subgraph deployments fail to index at any point
- mainnet: https://thegraph.com/hosted-service/subgraph/neokry/nouns-builder-mainnet
- goerli: https://thegraph.com/hosted-service/subgraph/neokry/nouns-builder-goerli
> Add subgraph

- .github/workflows/main.yml
> chore: update github workflow triggers

- apps/web/src/layouts/DefaultLayout/Nav.styles.css.ts
- apps/web/src/layouts/DefaultLayout/Nav.tsx
Fixes header issue for large screens
- is header fixed for large screens
- does the header still work for other screen sizes
> Fix header for large screens

- apps/web/.env
- apps/web/src/constants/defaultChains.ts
Chain slug does not match redirect config
does chain slug work with redirect for ethereum chain
> Fix ethereum chain slug

- apps/web/src/modules/auction/components/AllBids/BidCard.tsx
- apps/web/src/modules/auction/components/CurrentAuction/RecentBids.tsx
- apps/web/src/modules/auction/components/WinningBidder.tsx
- apps/web/src/modules/dao/components/About/Founder.tsx
- apps/web/src/modules/dao/components/About/Statistic.tsx
- apps/web/src/modules/dao/components/Activity/CurrentDelegate.tsx
- apps/web/src/modules/proposal/components/ProposalDescription/DecodedTransactions.tsx
- apps/web/src/modules/proposal/components/ProposalDetailsGrid/ProposalDetailsGrid.tsx
- apps/web/src/modules/proposal/components/ProposalHeader.tsx
Fixes etherscan links that we're not changed when transitioning to multichain
- are etherscan links fixed
> Fix etherscan links

- apps/web/src/components/Fields/StickySave.tsx
- apps/web/src/modules/create-dao/components/ReviewAndDeploy/ReviewAndDeploy.tsx
- apps/web/src/modules/create-dao/components/ReviewAndDeploy/SuccessfulDeploy.tsx
- apps/web/src/modules/create-proposal/components/ReviewProposalForm/ReviewProposalForm.tsx
- apps/web/src/modules/create-proposal/components/SelectTransactionType/AdminNav.tsx
- apps/web/src/modules/dao/components/Activity/DelegateForm.tsx
- apps/web/src/modules/dao/components/PreAuctionForm.tsx
- apps/web/src/modules/proposal/components/ProposalActions/VoteStatus/VoteModal.tsx
- replaces contract writes that used `useContract` with `prepareWriteContract` and `writeContract` to fix chainId issues
- replaces `Button` with `ContractButton` when executing a transaction to prevent chainId issues
transactions that used `useContract` would sometimes fail due to the signer not being on the right chain  
- do these contract writes work properly now
> Fix issue with contract writes

- apps/web/src/data/subgraph/requests/tokensQuery.ts
- apps/web/src/pages/profile/[user].tsx
- fixes broken link on profile page
- improves pagination on profile page
- do dao links on profile page work as expected
- does profile pagination correctly enable / disable arrows when needed
> Fix links and pagination on profile page

- apps/web/src/components/Home/GetStarted.tsx
Fixes issue where create dao button would not try to connect wallet properly
- does create dao button on homepage work if no wallet is connected
> Fix create dao button

- apps/subgraph/networks.json
- apps/web/src/constants/subgraph.ts
changes to new goldsky deployments
nouns builder has its own goldsky project
- does zora and zora-testnet work with new goldsky endpoints
> Update to new goldsky deployments

- apps/web/src/modules/create-proposal/components/TransactionForm/Airdrop/Airdrop.tsx
Updates airdrop transaction copy to remove confusion around the transaction.
fixes #292 
- is airdrop copy updated
> Update copy for airdrop transaction

- apps/web/src/modules/create-dao/components/GeneralForm/GeneralForm.tsx
Helper text was incorrect for dao website
- is website helper text correct
> Fix website helpertext

- README.md
- apps/subgraph/README.md
> Add new subgraph links to readme

- apps/web/src/data/subgraph/requests/exploreQueries.ts
- apps/web/src/data/subgraph/requests/homepageQuery.ts
- Fix type error for spam filter
- does spam filter work correctly
> Fix type issue for spam filter

- apps/web/package.json
- apps/web/src/pages/_app.tsx
- pnpm-lock.yaml
Adds loading bar for page transitions
- does loading bar properly show
> Add progress bar for page loading

- apps/web/src/data/subgraph/queries/proposalOGMetadata.graphql
- apps/web/src/data/subgraph/requests/proposalQuery.ts
- apps/web/src/data/subgraph/sdk.generated.ts
- apps/web/src/modules/auction/components/AuctionPaused.tsx
- apps/web/src/modules/proposal/components/ProposalCard.tsx
- apps/web/src/pages/dao/[network]/[token]/vote/[id].tsx
Update proposal page navigation to accept proposal numbers and proposal Ids
- do proposal pages work with proposal numbers and Ids
-
> Update proposal page to work with proposal numbers

- apps/web/src/pages/legal.tsx
> Update legal terms for bridge

- apps/web/.env
- apps/web/src/data/subgraph/queries/activeAuctions.graphql
- apps/web/src/data/subgraph/requests/homepageQuery.ts
- apps/web/src/data/subgraph/sdk.generated.ts
- changes ordering so DAOs are visible even when bids are not placed
- does the homepage query work as expected
> Update homepage query to order by auction end time

- apps/web/src/modules/auction/components/CurrentAuction/CurrentAuction.tsx
- apps/web/src/modules/auction/components/CurrentAuction/Settle.tsx
Implements the ask mentioned here: #269
> Changes "Settle Auction" button to "Claim NFT" or "Start next auction" based on connected wallet

- apps/web/src/pages/dao/[network]/[token]/vote/[id].tsx
> Flag potentially harmful proposals

- apps/web/src/modules/dao/components/AdminForm/AdminForm.tsx
- apps/web/src/modules/dao/utils/adminFormFieldToTransaction.tsx
- Fixes issue around admin form that surfaced after the wagmi upgrade
- does admin form work as intended
> Fix admin form issues

- apps/web/src/pages/dao/[network]/[token]/vote/[id].tsx
> Detects possible drains. 

- apps/web/src/modules/create-dao/components/AuctionSettingsForm/AuctionSettingsForm.tsx
> Add chris to voting delay / period flag

- apps/web/src/pages/dao/[network]/[token]/vote/[id].tsx
Fixes a proposal metadata issue introduced when we improved malicious proposal alerts.
> Fix proposal metadata

- apps/web/src/data/subgraph/requests/dashboardQuery.ts
- apps/web/src/modules/dashboard/Dashboard.tsx
We are experiencing outages and don't know which service it is coming from. 
This propagates the error message down to the view so we & the user can see what is down.
> Propagate Error Messages to View

- apps/web/package.json
- apps/web/src/pages/api/renderer/stack-images.ts
- pnpm-lock.yaml
Moves DAO image renderering functionality to this project
- ensure response from `/api/renderer/image-stack` match `api.zora.co/renderer/image-stack`
> Add stack images endpoint

- apps/web/src/pages/api/renderer/stack-images.ts
Single images had an incorrectly assumed image type.
> Fix issues with single images

- apps/web/src/modules/auction/components/AuctionImage.tsx
- apps/web/src/modules/dao/components/DaoCard/DaoCard.tsx
> Turn off optimization for DAO images

- apps/web/src/modules/create-proposal/components/ReviewProposalForm/ReviewProposalForm.tsx
> Simulate L2 transactions

- apps/web/src/constants/swrKeys.ts
- apps/web/src/data/subgraph/requests/averageWinningBid.ts
- apps/web/src/modules/auction/components/Auction.tsx
- apps/web/src/modules/auction/components/CurrentAuction/CurrentAuction.tsx
- apps/web/src/modules/auction/components/CurrentAuction/PlaceBid.tsx
- apps/web/src/modules/auction/components/CurrentAuction/WarningModal.tsx
Adds a warning modal to the place bid flow warning if their bid is 5x average winning bids or reserve price
closes #417
> Add warning modal to place bid flow

- apps/web/src/data/contract/abis/ManagerV2.ts
- apps/web/src/modules/create-dao/components/ReviewAndDeploy/ReviewAndDeploy.tsx
- apps/web/src/modules/create-proposal/components/Upgrade/Upgrade.tsx
- apps/web/src/modules/create-proposal/components/Upgrade/versions/2.0.0.md
- apps/web/src/modules/create-proposal/components/Upgrade/versions/index.ts
- apps/web/src/modules/create-proposal/constants/versions.ts
- apps/web/src/pages/dao/[network]/[token]/index.tsx
Adds support for the V2 manager.
- Ensure creating DAOs continues to work
> Add support for manager v2

- apps/web/src/modules/create-proposal/components/Upgrade/versions/2.0.0.md
Adds a link to the V2 upgrade audit in the upgrade proposal
Is the audit link in the upgrade proposal?
> Add audit info to V2 upgrade proposal

- apps/web/src/stores/useChainStore.tsx
Fixes an issue where chain store had breaking changes and did not use a new version
> Bump chain store version

- apps/web/src/data/contract/chains.ts
- apps/web/src/modules/create-dao/components/ReviewAndDeploy/ReviewAndDeploy.tsx
- apps/web/src/modules/create-proposal/components/Upgrade/versions/2.0.0.md
Adds protocol rewards disclaimer to DAO deploy and upgrade proposal
> Add protoocl rewards disclaimer

- apps/web/src/pages/dao/[network]/[token]/vote/[id].tsx
Changes vote warning to from danger style to warning style
> Change vote warning

- apps/web/src/constants/addresses.ts
Enables migration for lil toadz
> Enable migration for lil toadz

- apps/web/src/modules/proposal/components/ProposalVotes/ProposalVotes.tsx
Fixes an error where proposal max votes was incorrectly calculated
> Fix proposal votes calculations

- apps/web/src/modules/create-proposal/components/TransactionForm/CustomTransaction/forms/Summary/Summary.tsx
Fixes an issue where custom ABI could not be used in the transaction builder
> Fix abi issue on custom tx form

- apps/web/src/modules/create-dao/components/ReviewAndDeploy/ReviewAndDeploy.tsx
Encoding init params for token would fail due to viem changes
> Fix encoding error

- .husky/pre-commit
- .husky/pre-push
- funding.json
adding funding json and remove precommit hooks
> funding json

- apps/web/src/pages/about.tsx
- package.json
- pnpm-lock.yaml
> Update about page

- apps/web/src/modules/create-proposal/components/FixRendererBase/FixRendererBase.tsx
- apps/web/src/modules/create-proposal/components/FixRendererBase/index.ts
- apps/web/src/modules/create-proposal/components/FixRendererBase/summary.md
- apps/web/src/modules/create-proposal/components/TransactionForm/FixRendererBase/FixRendererBase.tsx
- apps/web/src/modules/create-proposal/components/UpgradeCard.tsx
- apps/web/src/modules/create-proposal/constants/transactionType.tsx
- apps/web/src/modules/create-proposal/hooks/index.ts
- apps/web/src/modules/create-proposal/hooks/useRendererBaseFix.ts
- apps/web/src/pages/dao/[network]/[token]/proposal/create.tsx
closes #515 
This is if user tries to create a proposal directly (existing proposal type, tweaked copy):
Shown as upgrade:
Upgrade button takes you to review page for proposal submission:
> added fix renderer base proposal type as an upgrade

- apps/web/src/modules/proposal/components/ProposalActions/VoteStatus/VoteModal.tsx
> fixed vote submitted popup

- apps/web/src/data/subgraph/queries/meta.graphql
- apps/web/src/data/subgraph/requests/sync.ts
- apps/web/src/data/subgraph/sdk.generated.ts
- apps/web/src/modules/auction/hooks/useAuctionEvents.ts
- apps/web/src/pages/dao/[network]/[token]/[tokenId].tsx
> added redirect for token not found + wait for subgraph sync

- apps/web/src/modules/create-proposal/components/TransactionForm/Escrow/Escrow.tsx
- apps/web/src/modules/create-proposal/components/TransactionForm/Escrow/EscrowDetailsDisplay.css.ts
- apps/web/src/modules/create-proposal/components/TransactionForm/Escrow/EscrowDetailsDisplay.tsx
- apps/web/src/modules/create-proposal/components/TransactionForm/Escrow/EscrowForm.schema.ts
- apps/web/src/modules/create-proposal/components/TransactionForm/Escrow/EscrowForm.tsx
- apps/web/src/modules/proposal/components/ProposalDescription/MilestoneDetails.tsx
- apps/web/src/utils/ens.ts
- apps/web/src/utils/yup/address.schema.ts
1. consolidate escrow proposal form errors; closes #552 
2. closes https://github.com/BuilderOSS/nouns-builder/issues/547
3. closes #548
> fix issues with escrow proposal

- .github/contributing.md
> docs: edited the discord link

- apps/web/src/components/Fields/SmartInput.tsx
- apps/web/src/components/Fields/styles.css.ts
- apps/web/src/hooks/useEnsData.ts
- apps/web/src/modules/create-proposal/components/TransactionForm/Airdrop/AirdropForm.schema.ts
- apps/web/src/modules/create-proposal/components/TransactionForm/Airdrop/AirdropForm.test.tsx
- apps/web/src/modules/create-proposal/components/TransactionForm/Airdrop/AirdropForm.tsx
- apps/web/src/modules/create-proposal/components/TransactionForm/SendEth/SendEth.schema.ts
- apps/web/src/modules/create-proposal/components/TransactionForm/SendEth/SendEth.tsx
- apps/web/src/pages/api/renderer/stack-images.ts
- apps/web/src/utils/ens.ts
- apps/web/src/utils/yup/address.schema.ts
> fix: support ens in address smart input

- README.md
> docs: removed the Builder Protocol link which no longer exists

- apps/web/src/components/Avatar/Avatar.tsx
- apps/web/src/components/Meta.tsx
- apps/web/src/layouts/DaoLayout.tsx
- apps/web/src/layouts/LayoutWrapper.tsx
- apps/web/src/pages/api/farcaster.ts
- apps/web/src/pages/api/og/dao.tsx
- apps/web/src/pages/api/og/proposal.tsx
- apps/web/src/pages/dao/[network]/[token]/[tokenId].tsx
- apps/web/src/pages/dao/[network]/[token]/proposal/create.tsx
- apps/web/src/pages/dao/[network]/[token]/proposal/review.tsx
- apps/web/src/pages/dao/[network]/[token]/vote/[id].tsx
- apps/web/src/utils/gradient.ts
closes https://github.com/BuilderOSS/nouns-builder/issues/367
> [prod] fix: og image meta tags for proposal / dao page

- apps/web/src/components/ContractButton.tsx
- apps/web/src/modules/proposal/components/PropDates/PropDateCard.tsx
- apps/web/src/modules/proposal/components/PropDates/PropDateForm.tsx
- apps/web/src/modules/proposal/components/PropDates/PropDateReplyCard.tsx
closes https://github.com/BuilderOSS/nouns-builder/issues/592
> added markdown support for propdates + fix submit button

- apps/web/src/components/Meta.tsx
- apps/web/src/modules/proposal/components/ProposalActions/CancelButton.tsx
- apps/web/src/pages/api/og/dao.tsx
- apps/web/src/pages/api/og/proposal.tsx
- apps/web/src/pages/dao/[network]/[token]/vote/[id].tsx
> Minor Bug fixes

- apps/web/src/hooks/useIsGnosisSafe.ts
- apps/web/src/modules/proposal/components/ProposalDescription/MilestoneDetails/index.tsx
- apps/web/src/pages/create.tsx
> fix: disable dao creation for gnosis safes

- apps/web/src/components/Icon/assets/erc20.svg
- apps/web/src/components/Icon/assets/nft.svg
- apps/web/src/components/Icon/icons.ts
- apps/web/src/constants/swrKeys.ts
- apps/web/src/data/contract/abis/ERC20.ts
- apps/web/src/hooks/useTokenMetadata.ts
- apps/web/src/modules/create-proposal/components/TransactionForm/SendErc20/SendErc20.schema.ts
- apps/web/src/modules/create-proposal/components/TransactionForm/SendErc20/SendErc20.tsx
- apps/web/src/modules/create-proposal/components/TransactionForm/SendErc20/index.ts
- apps/web/src/modules/create-proposal/components/TransactionForm/TransactionForm.tsx
- apps/web/src/modules/create-proposal/constants/transactionType.tsx
- apps/web/src/modules/proposal/components/ProposalDescription/DecodedTransactions/ArgumentDisplay.tsx
- apps/web/src/modules/proposal/components/ProposalDescription/DecodedTransactions/DecodedTransactions.tsx
- apps/web/src/modules/proposal/components/ProposalDescription/DecodedTransactions/DecodedValueRenderer.tsx
- apps/web/src/modules/proposal/components/ProposalDescription/DecodedTransactions/ERC20ArgumentDisplay.tsx
- apps/web/src/modules/proposal/components/ProposalDescription/DecodedTransactions/EscrowArgumentDisplay.tsx
- apps/web/src/pages/api/token-metadata.ts
- apps/web/src/services/alchemyService.ts
> feat: add erc20 transfer proposal type

- apps/web/src/constants/swrKeys.ts
- apps/web/src/data/contract/abis/ERC1155.ts
- apps/web/src/data/contract/abis/ERC721.ts
- apps/web/src/hooks/useNftMetadata.ts
- apps/web/src/modules/create-proposal/components/TransactionForm/SendErc20/SendErc20.tsx
- apps/web/src/modules/create-proposal/components/TransactionForm/SendNft/SendNft.schema.ts
- apps/web/src/modules/create-proposal/components/TransactionForm/SendNft/SendNft.tsx
- apps/web/src/modules/create-proposal/components/TransactionForm/SendNft/index.ts
- apps/web/src/modules/create-proposal/components/TransactionForm/TransactionForm.tsx
- apps/web/src/modules/create-proposal/constants/transactionType.tsx
- apps/web/src/modules/dao/components/Treasury/NFTBalanceDisplay.tsx
- apps/web/src/modules/proposal/components/ProposalDescription/DecodedTransactions/ArgumentDisplay.tsx
- apps/web/src/modules/proposal/components/ProposalDescription/DecodedTransactions/NFTArgumentDisplay.tsx
- apps/web/src/pages/api/nft-metadata.ts
- apps/web/src/services/alchemyService.ts
> feat: add nft transfer proposal type

- apps/web/src/modules/dao/components/MembersList/MembersList.tsx
- apps/web/src/modules/dao/components/MembersList/MembersListLayout.tsx
- apps/web/src/pages/api/membersList/[collectionId]/export.ts
> feat: added export delegates as csv button

- apps/subgraph/README.md
- apps/subgraph/package.json
- apps/subgraph/schema.graphql
- apps/subgraph/scripts/build.sh
- apps/subgraph/src/token.ts
- apps/web/src/constants/swrKeys.ts
- apps/web/src/data/subgraph/fragments/Snapshot.graphql
- apps/web/src/data/subgraph/queries/snapshots.graphql
- apps/web/src/data/subgraph/sdk.generated.ts
- apps/web/src/modules/proposal/components/ProposalVotes/ProposalVotes.tsx
> fix: total votes at snapshot in proposal page

- apps/web/src/components/Artwork/ArtworkPreview.tsx
- apps/web/src/components/Uploading/Uploading.tsx
- apps/web/src/layouts/CreateDaoLayout/CreateDaoLayout.tsx
- apps/web/src/modules/create-dao/components/Artwork/ArtworkUpload.tsx
- apps/web/src/modules/create-dao/stores/useFormStore.ts
- apps/web/src/modules/create-proposal/components/TransactionForm/ReplaceArtwork/ArtworkUpload.tsx
- apps/web/src/modules/create-proposal/components/TransactionForm/ReplaceArtwork/ReplaceArtworkForm.tsx
- apps/web/src/modules/create-proposal/stores/useArtworkStore.ts
- apps/web/src/pages/api/pin-cid.ts
- package.json
- packages/hooks/src/useArtworkUpload.ts
- packages/sdk/src/subgraph/requests/auctionHistory.ts
- packages/sdk/src/subgraph/requests/daoQuery.ts
- packages/sdk/src/subgraph/requests/daoVoters.ts
- packages/sdk/src/subgraph/requests/dashboardQuery.ts
- packages/sdk/src/subgraph/requests/exploreQueries.ts
- packages/sdk/src/subgraph/requests/getBids.ts
- packages/sdk/src/subgraph/requests/homepageQuery.ts
- packages/sdk/src/subgraph/requests/proposalQuery.ts
- packages/sdk/src/subgraph/requests/proposalsQuery.ts
- packages/sdk/src/subgraph/requests/sync.ts
closes https://github.com/BuilderOSS/nouns-builder/issues/357
closes https://github.com/BuilderOSS/nouns-builder/issues/655
> fix: replace artwork form with infinite loop

- apps/web/src/modules/dashboard/Dashboard.tsx
> feat: display succeeded proposals in dashboard
