apps/web/src/modules/dao/components/DaoCard/DaoCard.tsx, apps/web/src/modules/dao/components/DaoFeed/DaoFeedCard.tsx, apps/web/src/modules/dao/components/Explore/Explore.tsx, apps/web/src/modules/dao/components/Explore/ExploreMyDaos.tsx, apps/web/src/modules/dao/hooks/useDaoFeedCard.ts
In the return response we receive the token id of the current active auction. 
We should instead navigate directly to that given token id instead of to dao address to by-pass the re-direct.
=> Add tokenid to dao card navigation link

apps/web/src/modules/proposal/components/ProposalHeader.tsx, apps/web/src/pages/dao/[token]/index.tsx
Fixes an issue where proposal navigation would return to DAO token page without setting tab query parameter
fixes #124 
Does changing redirect in the DAO token page cause any other issues?
=> Fix navigation for proposal

apps/web/src/modules/create-dao/components/ReviewAndDeploy/ReviewAndDeploy.tsx
We have validations on the allocation form that should in theory catch undefined values for an allocation percentage. Seems like some users are somehow skipping this step, which causes a client side error on the review & deploy step when attempting to convert to a bignumber from an undefined value 
Add more safeguards around determining whether or not there might be any undefined allocation percentages.
Safely handle the bigNumber.from() given a defined value, and add a validation that prevents the user from proceeding if there happens to be an undefined allocation percentage.
=> Handle undefined allocation percentage values

apps/web/src/components/Home/VisitAlternate.tsx, apps/web/src/pages/index.tsx
Adds a link to visit testnet / mainnet on the homepage.
closes #143 
- Ensure mainnet / testnet links show up properly depending on environment chainid
- Ensure mainnet / testnet links correctly link out to the right application
- Should `VisitAlternate` be renamed to something else?
=> Add 'visit testnet / mainnet' to homepage

apps/web/src/pages/dao/[token]/[tokenId].tsx
Long og descriptions would change formatting on certain platforms.
N/A
- og metadata formats properly on all platforms
=> Fix issue with long og descriptions

apps/web/src/modules/create-dao/components/Artwork/ArtworkUpload.tsx
We're getting 404's resolving for ipfs files that might require file name sanitization
Turns out we are not sanitizing the path name when updating the url we store locally. This is causing the layers to 404 for unsanitised file paths.
=> update url path on artwork upload

apps/web/src/modules/dao/components/About/About.tsx
Founders with 0% allocation are not being filtered on DAO about page
fixes #178 
- are 0% founders being correctly filtered?
=> Fix issue where 0% allocation founders are not filtered

apps/web/src/modules/create-dao/components/AllocationForm/AllocationForm.schema.ts, apps/web/src/modules/create-dao/components/VetoForm.tsx
Address validation is debouncing for every call not on a per address basis causing validation issues when multiple address fields exist on one page.
- is address validation working properly
- are forms with multiple address fields debouncing properly
=> Fix address debounce issue

apps/web/src/modules/create-proposal/components/CreateProposalHeading.tsx, apps/web/src/modules/create-proposal/components/Queue/Queue.tsx, apps/web/src/modules/proposal/components/ProposalNavigation.tsx, apps/web/src/pages/dao/[token]/proposal/create.tsx
simplify proposal creation by moving transaction queue to a modal
- users were getting stuck on the proposal creation page 
- we need more room to add previews for bigger proposal templates like droposals
- are proposal template forms are still functioning correctly
- is the transaction queue modal retaining all functionality
=> Update create proposal flow

apps/web/src/modules/create-proposal/components/Queue/Queue.tsx, apps/web/src/modules/create-proposal/components/SelectTransactionType/SelectTransactionType.tsx, apps/web/src/modules/create-proposal/components/TransactionForm/Airdrop/Airdrop.tsx, apps/web/src/modules/create-proposal/components/TransactionForm/TransactionForm.tsx, apps/web/src/modules/create-proposal/components/TransactionTypeIcon.tsx, apps/web/src/modules/create-proposal/constants/transactionType.tsx, apps/web/src/pages/dao/[token]/proposal/create.tsx
We currently add updateMinters for each 'batch to' transaction, this turns out a bit lengthy for proposals (This happened on a recent airdrop proposal for the entropy dao) with a longer list of transactions.
As referenced here: https://nouns.build/dao/0x8983ec4b57dbebe8944af8d4f9d3adbafea5b9f1/vote/0x9b2610da3bbdee52076e52c6e1b3d17056fdf5b8d85d3bf0bd4bd33b2297c561
We should only add once, and make it visible as an un-editable transaction (similar to upgrades) if the treasury address is not a minter and UPDATE_MINTER is not already added to the transaction queue.
Are there open questions, risks or edge cases to watch for?
Added a fall back to the Transaction Type icon (to particularly handle cases where we want a default value for).
Create an airdrop for a dao where the minter is already …
=> Separate update minters transaction type

apps/web/src/utils/yup/url.schema.ts
The regex for URL validation does not ensure that the protocol is specified for the DAO website leading to multiple DAOs with broken links (test.com instead of https://test.com). This change removes the optional check for the protocol at the beginning of the string.
fixes #204 
- does website validation correctly require a protocol?
- should this issue be fixed in another way? (appending https to empty urls?)
=> Fix DAO website validation

apps/web/src/modules/proposal/components/ProposalCard.css.ts
Sets a max width for long proposal titles on desktop
closes #215 
do proposals format correctly on mobile and desktop for normal and long proposals
=> Fix style for long proposal titles

apps/web/src/modules/auction/components/CurrentAuction/PlaceBid.tsx
Fixes an issue where the place bid button would not show the connect wallet modal when user was not connected.
closes #212
replaces #213 
- does the place bid button show the connect wallet modal when a user is not connected
- does the button show the network modal when a user is on the wrong network
- does bidding still validate properly
=> Fix place bid button when no wallet is connected

apps/web/src/modules/create-proposal/components/TransactionForm/CustomTransaction/forms/Summary/Summary.tsx, apps/web/src/modules/create-proposal/components/TransactionForm/Droposal/Droposal.css.ts, apps/web/src/modules/create-proposal/components/TransactionForm/Droposal/DroposalPreview.tsx
Long text on custom transaction + droposal proposal templates was not being wrapped properly.
closes #240 
Does text wrap properly
=> Fix formatting issues with long text on proposal templates

apps/web/src/pages/dao/[token]/vote/[id].tsx
Adds `addresses` back to proposal page SSR data.
Removing `addresses` from SSR broke the voter participation rate query
does this fix voter participation query
=> Fix voter participation rate not loading

apps/web/src/components/Fields/DaysHoursMinsSecs.tsx, apps/web/src/modules/create-dao/components/AuctionSettingsForm/AuctionSettingsForm.schema.ts, apps/web/src/modules/create-dao/components/AuctionSettingsForm/AuctionSettingsForm.tsx, apps/web/src/modules/create-dao/components/ReviewAndDeploy/ReviewAndDeploy.tsx, apps/web/src/modules/create-dao/stores/useFormStore.ts
adds voting delay and period controls for authorized accounts
Certain DAOs need to be created with modified voting delay and period settings due to time constraints.
- does creating a DAO with a non authorized account work with expected defaults
- does creating a DAO with an authorized account show the correct contract
- does deploying a DAO with modified voting delay and period work correctly
- are delay / period constrained to the correct min / max values
=> Add voting delay and period settings for authorized accounts

apps/web/src/modules/create-proposal/components/TransactionForm/Droposal/Droposal.tsx, apps/web/src/modules/create-proposal/components/TransactionForm/Droposal/DroposalForm.schema.ts, apps/web/src/modules/create-proposal/components/TransactionForm/Droposal/DroposalForm.tsx, apps/web/src/modules/create-proposal/components/TransactionForm/Droposal/DroposalPreview.tsx
- Add a default value for `maxSalePurchasePerAddress`
- Add a default value for `editionSize`
- Add required validation for `editionSize`
- `maxSalePurchasePerAddress` did not include a fallback value if the user removed the default value / didn't provide their own. It should be set it `UINT_32_MAX`
- `editionSize` was left set to zero on an open edition. Zora contracts require it to be set to `UINT_64_MAX`
- `editionSize` did not have a required validation so an issue could occur if the user left it  blank
- does creating a droposal with no maxSalePurchasePerAddress work
- does creating a droposal as an open edition work
- is `editionSize` now required
=> Fix droposal open edition issues

apps/web/src/components/Fields/Date.tsx, apps/web/src/modules/create-proposal/components/TransactionForm/Droposal/DroposalForm.tsx
Changes droposal date control to include time as well as format in ISO format to fix timezone issues.
- users are seeing discrepancies in the inputted dates vs actual dates due to timezone issues
- users could not set a time for droposals
- does the new datepicker for droposals 
- do droposals correctly handle timezones now
- do the time controls work on the datepicker
- do the time controls introduce issues in other components the datepicker is used in
=> Fix timezone and datepicker issues with droposal

.github/workflows/main.yml
Breaks out lint, type-check and test to their own CI tasks
changed to ensure we can view lint and type-check results for external contributors 
does the CI config still work as expected
=> Change CI to run lint, type-check and test separately

apps/web/src/layouts/DefaultLayout/NavMenu.tsx
Adds `egar` to chain logos in chain switcher
improve chain logo loading speed in switcher since they are hidden by default
=> Fix chain logo loading speed

apps/web/src/pages/dao/[network]/[token]/[tokenId].tsx
Fixes an issue where admin section was not shown when a DAO did not have feeds enabled
fixes #304 
- is admin tab visible for daos with feeds disabled
=> Fix issue where admin page is not properly shown

apps/web/src/utils/provider.ts
updates `getProvider` implementation to use a map to store multiple providers instead of a single provider
get provider was only instantiating once and caching based on the first chain it was called with causing issues when a user would switch chains
- does getProvider work properly on multichain 
- can test via send eth  and other proposal templates that utilize it
=> Fix issue with get provider function

apps/web/src/data/subgraph/queries/exploreDaosPage.graphql, apps/web/src/data/subgraph/requests/exploreQueries.ts, apps/web/src/data/subgraph/sdk.generated.ts, apps/web/src/modules/dao/components/Explore/Explore.tsx, apps/web/src/pages/api/explore.ts, apps/web/src/pages/explore.tsx
Fixes pagination on explore page, and explore api. Updates helper text for when a user is on a page > 1 and no daos are returned.
- users were navigating to pages with no daos on the explore page due to pagination being disabled only when no daos were returned and not when daos.length < limit
- pagination on explore api incorrectly assumed pages started at 0
- is pagination showing all pages on the explore page
- is pagination disabled at the right times on the explore page
=> Fix explore pagination

apps/web/src/modules/create-dao/components/ReviewAndDeploy/ReviewAndDeploy.tsx
Adds a new confirmation to `ReviewAndDeploy` for users to confirm what chain they want to deploy on
closes #312 
- does confirmation on deployment page function properly
=> Add chain confirmation to DAO deploy page

apps/web/src/layouts/DefaultLayout/NavMenu.tsx
set `isOpenChainMenu` to false when active dropdown is not `chainMenu`
fixes #311 
- does chain dropdown close when a user selects their profile
=> Fix chain dropdown not closing

apps/web/src/modules/dao/components/MembersList/MemberListCard.tsx, apps/web/src/modules/dao/components/MembersList/MembersListLayout.tsx
Fixes misaligned margins 
Margins got messed on my last push.
=> fix margin error

apps/web/src/modules/dao/components/DaoFeed/DaoErrorFeed.tsx, apps/web/src/modules/dao/components/DaoFeed/DaoFeed.tsx, apps/web/src/modules/dao/components/DaoFeed/DaoFeedCard.tsx, apps/web/src/modules/dao/components/DaoFeed/DaoFeedSkeleton.tsx, apps/web/src/pages/index.tsx
- Changes recent daos feed to only show when a dao has at least 3 daos. 
- Adds skeleton loading to recent daos feed
- Recent daos component still displays even when a network has no daos
- does recent daos feed display when a network has > 2 daos
- does recent daos feed hide then a network has < 3 daos
- does new skeleton loading work
=> Hide recent DAOs when a network has less than 3 DAOs

apps/web/src/data/subgraph/fragments/AuctionBid.graphql, apps/web/src/data/subgraph/queries/auctionBids.graphql, apps/web/src/data/subgraph/sdk.generated.ts, apps/web/src/modules/auction/components/AllBids/AllBids.tsx, apps/web/src/modules/auction/components/AllBids/BidCard.tsx, apps/web/src/modules/auction/components/Auction.tsx, apps/web/src/modules/auction/components/BidHistory.tsx, apps/web/src/modules/auction/components/CurrentAuction/CurrentAuction.tsx, apps/web/src/modules/auction/components/CurrentAuction/RecentBids.tsx
Updates bid history to use subgraph
- fixes bid history issues when rpc does not support `getLogs` calls
- fetches bid history faster
- do auction bids fetch correctly
=> Change bid history to use subgraph

apps/web/src/modules/create-dao/components/AllocationForm/AllocationForm.schema.ts, apps/web/src/modules/create-dao/components/VetoForm.tsx, apps/web/src/modules/create-proposal/components/TransactionForm/Airdrop/AirdropForm.schema.ts, apps/web/src/modules/create-proposal/components/TransactionForm/CustomTransaction/forms/Address/Address.tsx, apps/web/src/modules/create-proposal/components/TransactionForm/CustomTransaction/forms/Address/fields.ts, apps/web/src/modules/create-proposal/components/TransactionForm/Droposal/DroposalForm.schema.ts, apps/web/src/modules/create-proposal/components/TransactionForm/SendEth/SendEth.schema.ts, apps/web/src/modules/dao/components/Activity/DelegateForm.schema.ts, apps/web/src/modules/dao/components/Activity/DelegateForm.tsx, apps/web/src/modules/dao/components/AdminForm/AdminForm.schema.ts, apps/web/src/stores/useChainStore.tsx, apps/web/src/utils/ens.ts, apps/web/src/utils/getChainFromLocalStorage.ts, apps/web/src/utils/yup/address.schema.ts, apps/web/src/utils/yup/index.ts
- create a shared address validation schema `address.schema.ts`
- updates `isValidAddress` to return a value and an error
- updates `isValidAddress` to prevent users from using ENS names resolving to contracts on L2 (these contracts are not guaranteed to exist on the same address)
- prevent users from adding incorrect addresses as founders / recipients 
- do addresses inputs validate L2 ens names properly (EOAs should work, smart contracts should not, plain addresses should work)
=> Add proper validation for L2 ens names

apps/web/src/modules/dao/components/DaoFeed/DaoFeed.css.ts
=> Fix bug with dao feed grid

apps/web/src/data/subgraph/queries/activeAuctions.graphql, apps/web/src/data/subgraph/queries/activeDaos.graphql, apps/web/src/data/subgraph/requests/exploreQueries.ts, apps/web/src/data/subgraph/requests/homepageQuery.ts, apps/web/src/data/subgraph/sdk.generated.ts
- filters daos with total auction amount less than 0.001 ETH on L2
- ideally this would only take 1 query to filter and pull dao data instead of 2 but this will be a temp measure until we can rework the explore page.
- l2 networks are getting spammed with airdrop farmers
- are daos with less than 0.001 ETH total auction sales filtered on L2
=> Add filter for spam daos on L2

apps/web/src/modules/proposal/components/ProposalDescription/DecodedTransactions.tsx
Fixes an issue where proposal value would not display when transaction calldata could not be deocded
=> Display value when proposal calldata cannot be decoded

apps/web/src/pages/dao/[network]/[token]/vote/[id].tsx
warning banner renders "0" on some pending proposals
- does warning banner render correctly for pending proposals
=> Fix bug with proposal warning banner

apps/web/src/hooks/useVotes.ts, apps/web/src/modules/proposal/components/ProposalActions/ProposalActions.tsx, apps/web/src/pages/dao/[network]/[token]/vote/[id].tsx
Adds ``keepPreviousData : true`` to useContractReads to useVotes hook and ProposalActions 
wagmi useContractReads hook was forcing page re-renders due to a bug with state/caching persistence 
https://github.com/wagmi-dev/wagmi/issues/2878
Took a bit of digging, but I was able to find a parameter that would stop this from happening 
``keepPreviousData : true``
This solves both issues: 
1) Proposal description and title being deleted on first login on network switch
2) Vote modal closing and deleting vote reason data on vote page.
=> fix useContractReads state dumping

apps/web/src/modules/proposal/components/ProposalActions/VoteStatus/VoteModal.tsx
Prevents the user from clicking away and deleting their vote data. 
Provides a corner aligned 'X' square to close the modal. 
https://github.com/ourzora/nouns-builder/issues/394
=> add close corner button

apps/web/src/components/Meta.tsx, apps/web/src/pages/dao/[network]/[token]/[tokenId].tsx
Implement Warpcast NFT meta tags, so that links shared on Farcaster render as NFTs rather than plain OG links.
Seen a couple people asking about this in the Builder channel on FC: https://warpcast.com/valcoholics/0x49a1cc8a
First time contributor and don't have the repo set up to be able to test locally. Would appreciate if someone could help me test! (I can check that the tags are working on the preview, but haven't run the linter etc)
=> Add Farcaster NFT meta tags

apps/web/src/modules/dashboard/DaoAuctionCard.tsx, apps/web/src/pages/api/renderer/stack-images.ts
- Fixes an issue where svgs did not render properly
- Adds unoptimized to DAO dashboard images
=> Fix svgs and dashboard image

apps/web/src/pages/api/renderer/stack-images.ts, apps/web/src/pages/dao/[network]/[token]/[tokenId].tsx
Fixes a bug where the image renderer could not handle images with different sizes
=> FIx image stacker issue

apps/web/src/modules/create-proposal/hooks/useAvailableUpgrade.ts
- Fixes an issue where an upgrade is shown even if the DAO is using the latest contracts. 
- Changes `useAvailableUpgrade` hook to checksagainst each individual contract version instead of checking against the manager version.
- Ensure no upgrade is shown if DAO is on the latest contracts.
- Ensure an upgrade is shown if a DAO is not on the latest contracts.
=> Fix issue with availible upgrade hook

apps/web/src/modules/auction/components/Auction.tsx
Fixes an issue where auctions for tokenId 0 would only show bid history and not auctions controls.
Are bid controls shown for tokenId 0
=> Fix tokenId 0 auction issue

apps/web/src/modules/create-dao/components/ReviewAndDeploy/ReviewAndDeploy.tsx
DAO deployment button is disabled for L1 because of the protocol rewards check not being shown for them.
Is the DAO deployment enabled for L1 chains.
=> Fix an issue where L1 deployment was disabled

apps/web/package.json, apps/web/src/data/contract/abis/Auction.ts, apps/web/src/modules/auction/components/Auction.tsx, apps/web/src/modules/auction/components/CurrentAuction/CurrentAuction.tsx, apps/web/src/modules/auction/components/CurrentAuction/PlaceBid.tsx
Allows users to set the `referral` query string parameter on the auction page to use `bidWithReferral` function. value from `referral` query string will be used as the auction referral. 
- Do auction referrals work for DAOs on V2
- Do auctions work like normal when no referral is set
- Do auction work like normal when a DAO is on V1
=> Add referral system

apps/subgraph/schema.graphql, apps/subgraph/src/governor.ts, apps/subgraph/src/metadata.ts, apps/subgraph/subgraph.yaml
This is a small change to add the hash of a proposal's execution to the Proposal entity in the subgraph when the Proposal is actually executed.
This is needed to get the hash of the migration transaction on the L1 side, in order to get the Merkle root on the L2 side.
Will need to deploy - I'm not sure exactly how to do this.
=> Add transaction hash of executed proposal to subgraph

apps/web/package.json, apps/web/src/data/contract/abis/Auction.ts, apps/web/src/modules/dao/components/AdminForm/Section.tsx, apps/web/src/modules/dao/components/PreAuctionForm.schema.ts, apps/web/src/modules/dao/components/PreAuctionForm.tsx, apps/web/src/utils/yup/address.schema.ts
Adds founder rewards config to preauction page
- Does setting auction rewards work on preauction page for V2 DAOs
- Does preauction page function as expected for V1 DAOs
=> Add auction rewards to preauction page

apps/web/src/modules/create-proposal/hooks/useAvailableUpgrade.ts
Adds default version so upgrade hook will work with DAOs still on V1.0.0
Does upgrade work for DAOs on V1.0.0
=> Add default version to upgrade hook

apps/web/src/pages/dao/[network]/[token]/index.tsx
Allow users to add referral param to `/dao/zora/0x32297b7416294b1acf404b6148a3c58107ba8afd` urls where no tokenId is specified.
- Does query string follow the redirect for links with no tokenId
=> Add referral query param to token redirect

apps/web/src/pages/api/migrate/attributes.ts, apps/web/src/pages/api/migrate/snapshot.ts, apps/web/src/pages/api/migrated.ts
Adds wagmi server config to functions that did not have it and used wagmi to fetch data.
=> Add wagmi server config

apps/web/src/data/subgraph/requests/daoMetadata.ts
Fixes issue where DAO address was not lowercased on metadata query
=> Fix DAO metadata query

apps/web/src/constants/etherscan.ts
Remove trailing forward slashes from certain Etherscan base URL constants to fix broken links.
Currently Etherscan links created for Optimism Sepolia, Base, Base Sepolia, Zora, and Zora Sepolia are broken because of an additional forward slash when concatenating URLs. It affects any component that includes an Etherscan URL for those chains.
=> Fix broken Etherscan links for certain chains

apps/web/src/modules/create-proposal/components/TransactionForm/CustomTransaction/forms/Arguments/Arguments.tsx
Fix an issue where array values for custom transactions are not validated properly due to the viem upgrade.
Are array values in custom transactions properly validated?
=> Fix issue where array data is not properly validated

apps/web/src/modules/dao/components/DaoFeed/DaoFeedSkeleton.tsx, apps/web/src/modules/dashboard/DaoAuctionCard.tsx, apps/web/src/pages/profile/[user].tsx, apps/web/src/utils/helpers.ts, packages/zoralabs-zord/src/theme.css.ts
Adds individual links for each DAO on the user profile page "DAOs" list. Previously it was a somewhat-confusing list of text strings. This feature ideally improves user experience and helps users discover new DAOs when viewing other users' profiles pages.
Previously it was a somewhat-confusing list of text strings. This feature ideally improves user experience and helps users discover new DAOs when viewing other users' profiles pages.
I also removed a prop that had the name `key` from the `DaoFeedCardSkeleton` component. `key` is a reserved word in React and cannot be used as a prop name. It also served no function as the parent component is already uniquely identified by the same key.
=> feat: make DAO list linkable in user profile

apps/web/src/modules/auction/components/CurrentAuction/Bidder.tsx
User story: As a user, I would like to navigate to recent bidders' profile pages while an auction is ongoing to see their other DAOs and NFT collection
Improves user-friendliness
3-liner
=> feat: Link recent bidders to their profile pages

apps/web/src/pages/api/og/dao.tsx
First convert result to BigInt, then format it with formatEther() which returns a decimal string. Never pass a decimal string into BigInt().
Also changes "id" to a random integer for these reasons:
1.	Prevents conflicts when making multiple simultaneous requests.
2.	Helps with debugging by ensuring request-response pairs can be uniquely identified.
3.	Follows JSON-RPC best practices for tracking responses.
Fixes this intermittent bug: 
How it looks fixed:
=> fix: convert properly before using BigInt

apps/web/src/data/subgraph/requests/homepageQuery.ts
This PR addresses an issue in the highestBidsRequest function where auctions with bugged or extremely distant endTime values (e.g., thousands of hours from now) were incorrectly included in the response and displayed on the nouns.build Home Page.
✅ What was changed:
Added a 30-day upper bound to the endTime filter
Some auctions were returning corrupted or unrealistic endTime values, which led to:
- Display bugs like Ends in 232404h
- Irrelevant data being shown to users
- Restricting endTime to within 30 days ensures only timely, relevant auctions are displayed.
Before (bugged timestamps):
After (filtered correctly):
**PS: The 3rd image is not loading due zora api stack image error.**
An image fallback was not added at this PR cause I could not confirm the correct image using OpenSea.
=> fix: Prevents auctions with bugged timestamps at HomePage

packages/ipfs-service/src/gateway.ts
This PR improves the image loading experience for DAOs by gracefully handling errors from the Zora image renderer and attempting a fallback using the Nouns Builder endpoint.
Some DAO Images was not loading on Home Page which resulted in a poor visual experience on the frontend. 
Updated the <Image /> component at apps/web/src/modules/dao/components/DaoCard/DaoCard.tsx to:
- Detect when tokenImage from api.zora.co fails.
- Automatically switch to nouns.build/api/renderer/stack-images as a fallback.
- If both sources fail, default to /ImageError.svg.
=> Fix: Add fallback to nouns.build image renderer if api.zora.co fails

apps/web/src/pages/api/generate-jwt.tsx, packages/hooks/src/useArtworkUpload.ts, packages/ipfs-service/src/upload.ts
also removes batching of directory upload at 150 files per batch - this needs contract changes to be able to work.
=> feat: re-add support for legacy pinata upload
